# Makefile
# See https://docs.cocotb.org/en/stable/quickstart.html for more info

# defaults
SIM ?= icarus
FST ?= -fst # Use more efficient FST format
TOPLEVEL_LANG ?= verilog
SRC_DIR = $(PWD)/../src
PROJECT_SOURCES = project.v counter4bit.sv sram.sv mnist_loader.sv \
                  load_conv_op_3x6.sv \
                  conv_weights_3x3_l1.sv conv_weights_3x3_l2.sv \
                  conv_weights_2x2_l3.sv \
                  conv_layer1.sv conv_layer2.sv conv_layer3.sv \
                  classification_tree.sv \
                  maxpool_2x2.sv \
                  main.sv

ifneq ($(GATES),yes)

# RTL simulation:
SIM_BUILD				= sim_build/rtl
COMPILE_ARGS    += -DFUNCTIONAL
VERILOG_SOURCES += $(addprefix $(SRC_DIR)/,$(PROJECT_SOURCES))
# Add the sram macro
VERILOG_SOURCES += $(PWD)/../macros/SRAM/RM_IHPSG13_1P_256x8_c3_bm_bist.v

else

# Gate level simulation:
SIM_BUILD				= sim_build/gl
COMPILE_ARGS    += -DGL_TEST
COMPILE_ARGS    += -DFUNCTIONAL
COMPILE_ARGS    += -DSIM
VERILOG_SOURCES += $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_io/verilog/sg13g2_io.v
VERILOG_SOURCES += $(PDK_ROOT)/ihp-sg13g2/libs.ref/sg13g2_stdcell/verilog/sg13g2_stdcell.v

# this gets copied in by the GDS action workflow
VERILOG_SOURCES += $(PWD)/gate_level_netlist.v

endif

# Allow sharing configuration between design and testbench via `include`:
COMPILE_ARGS 		+= -I$(SRC_DIR)

# Include the behavioural macros:
VERILOG_SOURCES += $(PWD)/macros/RM_IHPSG13_1P_core_behavioral_bm_bist.v

# Include the testbench sources:
VERILOG_SOURCES += $(wildcard $(PWD)/testbenches/*.v) $(wildcard $(PWD)/testbenches/*.sv)
TOPLEVEL ?= tb

# Specify where the python files can be found for testing
export PYTHONPATH := $(PWD)/testmodules:$(PYTHONPATH)

# List test modules to run, separated by commas and without the .py suffix:
COCOTB_TEST_MODULES ?= test

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
