/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module RM_IHPSG13_1P_256x8_c3_bm_bist(A_CLK, A_MEN, A_WEN, A_REN, A_ADDR, A_DIN, A_DLY, A_DOUT, A_BM, A_BIST_CLK, A_BIST_EN, A_BIST_MEN, A_BIST_WEN, A_BIST_REN, A_BIST_ADDR, A_BIST_DIN, A_BIST_BM);
  input A_CLK;
  wire A_CLK;
  input A_MEN;
  wire A_MEN;
  input A_WEN;
  wire A_WEN;
  input A_REN;
  wire A_REN;
  input [7:0] A_ADDR;
  wire [7:0] A_ADDR;
  input [7:0] A_DIN;
  wire [7:0] A_DIN;
  input A_DLY;
  wire A_DLY;
  output [7:0] A_DOUT;
  wire [7:0] A_DOUT;
  input [7:0] A_BM;
  wire [7:0] A_BM;
  input A_BIST_CLK;
  wire A_BIST_CLK;
  input A_BIST_EN;
  wire A_BIST_EN;
  input A_BIST_MEN;
  wire A_BIST_MEN;
  input A_BIST_WEN;
  wire A_BIST_WEN;
  input A_BIST_REN;
  wire A_BIST_REN;
  input [7:0] A_BIST_ADDR;
  wire [7:0] A_BIST_ADDR;
  input [7:0] A_BIST_DIN;
  wire [7:0] A_BIST_DIN;
  input [7:0] A_BIST_BM;
  wire [7:0] A_BIST_BM;
endmodule
